### PR TITLE
fix #10: don't assume obj prop in indexLinks

### LINKED ISSUE #10: Malformed Mentions array crashes sbot
A malformed mentions array will crash this module and consequently crash _sbot_ itself.

If mentions contain an element that doesn't contain a `link` property, everything crashes. The error can be traced back to line 75 of this module which makes the assumption of a well-formed array.

### PR DESCRIPTION
**Pull request by soapdog**
After breaking my _sbot_ five times today I came to realize that having a broken _mentions_ array in a post will prevent _sbot_ from starting. This was narrowed down to this module assuming all links in `indexLinks` were either a string or an object with a `link` property. I've added code to ignore items that are not these two cases.

### CODE REVIEW

**Comment by soapdog** [comment]
I've requested a review from a bunch of people that knows more than I do. I haven't tested this code as my flume dbs are in the process of synchronizing again.

File: index.js [hunk 1]
```diff
@@ -64,30 +64,37 @@ exports.indexLinks = function (message, opts, each) {
...
+  var any = !(msg || feed || blob)
 
   traverse(toMsgContent(message), function (obj, rel) {
     if (opts.rel && rel !== opts.rel) return
 
-    var r = (typeof obj == 'string') ? obj : obj.link
+    var r;
+    if (typeof obj == 'string') {
+      r = obj
+    } else if (typeof obj.link !== "undefined") {
```
Comment (christianbundy) [inline index.js]: Is there any case where this wouldn't be a string? We might be able to be more specific here.

Comment (soapdog) [reply index.js]: @christianbundy as far as I know, a mentions array can be something like:

```
[
  "#patchfox",
  {link: "#patchfox"},
  {name: "andre", link: "48634786"}
]
```
So you can have a literal string, or an object with a link but you shouldn't have something that is not one of those two cases but since we're talking about people building their own clients, they will make mistakes, there will be broken messages and we might want to code around it because one it is on the feed, it is there kinda forever.

Comment (christianbundy) [reply index.js]: Right, I agree with you. My concern is:

```json
[
  "#patchfox",
  {
    "link": { "foo": { "bar": [] } }
  }
]
```

This passes `typeof obj.link !== 'undefined'`, but if we take that value and pass it to ssb-ref and friends as a *string* then it seems like we'll break something. You know what I mean?

Comment (soapdog) [reply index.js]: oooohhh, I see... makes sense. Let me amend the commit

Comment (soapdog) [reply index.js]: Pushed a change with a better check, it is down below.

**Review by christianbundy — APPROVED** [review]
LGTM!

**Comment by HendrikPetertje** [comment]
Aha! this should fix my ongoing sbot issues as well then. I've been dealing with (probably) the same post creating the same troubles

**Comment by HendrikPetertje** [comment]
Question here (that I've also asked here: `%1yh3o3s6FOjpI/bdSFhxQKG52NCIKGDrDHmucr8qnFQ=.sha256`)

Is there any checking going on prior to messages being pulled into ssb-msgs? In this case the mentions array was just broken, but it could probably be just about any field right? is it an idea to put some kind of validation in place at the start of parsing a message that checks if all the "required and optional" fields are of the correct object-type (string, array, object, boolean, etc.) and ignore messages that don't follow the pre-defined specifications for that specific message type? (post, vote, git-commit, etc.)?

File: index.js [hunk 2]
```diff
@@ -64,30 +64,37 @@ exports.indexLinks = function (message, opts, each) {
...
+  var any = !(msg || feed || blob)
 
   traverse(toMsgContent(message), function (obj, rel) {
     if (opts.rel && rel !== opts.rel) return
 
-    var r = (typeof obj == 'string') ? obj : obj.link
+    var r;
+    if (typeof obj == 'string') {
+      r = obj
+    } else if (typeof obj.link == 'string') {
```
Comment (HendrikPetertje) [inline index.js]: I just tested this and the server still crashes over this line right here.

The content of `message` is:

```
{ type: 'post',
  text: '[SoapDog (SurfaceGo)](@qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=.ed25519) do I have a bug in mentions? #patchfox',
  root: '%oxXKoCVtqM111XqKyTyTOCXt6s/51/xI01O8F7DBbRQ=.sha256',
  branch: '%K+hbT4mTrcGgg17kwt86aoimRBtFHry1bcJFDdY7SlU=.sha256',
  mentions:
   [ { link: '@qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=.ed25519',
       name: 'SoapDog (SurfaceGo)' },
     null ],
  channel: 'patchfox' }
```
Apparently one of the mentions in the message is a nul (and somehow my database was fine pulling that down somehow)

the content of `obj` is: `null`
the content of `rel` is: `mentions`

The error produced is:

```
/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:81
    } else if (typeof obj.link == 'string') {
                          ^

TypeError: Cannot read property 'link' of null
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:81:27
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:50:9
    at Array.forEach (<anonymous>)
    at traverse (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:49:11)
    at Object.exports.indexLinks (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:72:3)
    at indexMsg (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-db/indexes/links.js:25:10)
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-db/indexes/links.js:34:12
    at reduce (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-db/node_modules/flumeview-level/index.js:90:25)
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/pull-write/index.js:35:23
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/pull-write/index.js:41:13
```

I'm unsure what to do with this

Comment (HendrikPetertje) [reply index.js]: an easy fix would be to:

```
} else if (obj && obj.link == 'string') {
```

But I doubt if we shouldn't fix things higher up the stack instead

Comment (soapdog) [reply index.js]: amending the PR...

Comment (soapdog) [reply index.js]: I've fixed with the code you've sent.

**Comment by HendrikPetertje** [comment]
Your last thingy seems to work! I don't really like the fix though. it's basically a guard clause after a type-check. would be nice to do that the other way around. 

That plus, this is mentions, but this kind of stuff could pretty much happen everywhere right? It would be kind of nice if we could do some kind of check on the "quality" in either `ssb-db` or `pull-write`. I probably have not that big of a say here, so feel free to ignore my last comment.

---
After testing, I made sure that the broken message can't be relayed through my pub (I removed the feed and blocked the author) all other pubs would pretty much just stop working when they try to download the message. These 2 steps should for now make sure that the issue doesn't spread to fast (unless people wifi-share and p2p directly with each other), allowing the big clients to update their code-bases before we allow this specific broken message to walk through the network freely.

**Comment by mixmix** [comment]
Don't have time to look at this in detail at the moment, but wanted to drop a resource.
I would like to propose it would be safer / easier to scoop out all the if else logic and use JSON schemas, I think they will be a much better time and way more fun.
AND they're already written: 
https://github.com/ssbc/ssb-schema-definitions/blob/master/index.js#L17-L59

Here's how you can use definitions that have been imported: https://github.com/ssbc/ssb-poll-schema/blob/master/v1/poll-update/schema/pollUpdate.js#L32-L35

If this is relevant and anyone needs help threading this in, hit me up.

**Comment by ahdinosaur** [comment]
what's the status on this being fixed and merged into `ssb-server`? i notice that 1/3 of my pubs (one.butt.nz) are permanently down because of this bug. :bug: 

```
/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:75
    var r = (typeof obj == 'string') ? obj : obj.link
                                                 ^

TypeError: Cannot read property 'link' of null
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:75:50
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:50:9
    at Array.forEach (<anonymous>)
    at traverse (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:49:11)
    at Object.exports.indexLinks (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:72:3)
    at indexMsg (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-db/indexes/links.js:25:10)
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-db/indexes/links.js:34:12
    at reduce (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/flumeview-level/index.js:90:25)
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/pull-write/index.js:35:23
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/pull-write/index.js:41:13
```

**Comment by christianbundy** [comment]
I thought it was fixed in this branch. I approved the PR, I *think* it just needs a merge, release, and a an update to ssb-server (although last I checked the tests were failing and I couldn't update any npm deps).

On Fri, Aug 9, 2019, at 16:09, Mikey wrote:
> what's the status on this being fixed and merged into `ssb-server`? i notice that 1/3 of my pubs (one.butt.nz) are permanently down because of this bug. 🐛

> `/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:75
    var r = (typeof obj == 'string') ? obj : obj.link
                                                 ^

TypeError: Cannot read property 'link' of null
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:75:50
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:50:9
    at Array.forEach (<anonymous>)
    at traverse (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:49:11)
    at Object.exports.indexLinks (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-msgs/index.js:72:3)
    at indexMsg (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-db/indexes/links.js:25:10)
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-db/indexes/links.js:34:12
    at reduce (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/flumeview-level/index.js:90:25)
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/pull-write/index.js:35:23
    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/pull-write/index.js:41:13
`

**Comment by christianbundy** [comment]
@soapdog Is this ready to merge, or does it need some more work?

**Comment by soapdog** [comment]
@christianbundy I haven't touched this since Jul 25th. I will double check if it still works.

**Comment by HendrikPetertje** [comment]
\o/
